[package]
name = "utxos"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.69"
bitcoincore-rpc = "0.16.0"
csv-async = {version="1.2.5", features=["tokio"]}